### ISSUE TITLE
vikplan2

### ISSUE THREAD

**Issue by vRenat** [RinatG/vikplan.com#20]
Привет! В калькуляторе зданий (https://vikplan2.ru/buildings) нельзя выбрать уровень стартового дворца (кроме нескольких фиксированных значений 1, 21, 31).
Почему нельзя выбирать конкретное значение? Сейчас в игре у большинства 35-36 уровни замка.

**Comment by RinatG** [comment]
это - фильтр уровней зданий для списка ниже. нужен для удобства, чтобы слишком длинные строки не были с переносами, особенно на мобильных устройствах.
фильтр "35" добавить можно, но он не улучшит пользовательский опыт, а не ПК браузерах страница будет выглядеть куце.
