### ISSUE TITLE
vikplan2 - скорость изучения знания

### ISSUE THREAD

**Issue by torrenton** [RinatG/vikplan.com#21]
Добрый день!
Подскажите пожалуйста, почему в новых тайных знаниях не отображается скорость изучения во времени?
К примеру - Знания - Тайные II - Защита (4-й уровень).
Ссылка - https://vikplan2.ru/research/secret2dfnc
![vikplan](https://user-images.githubusercontent.com/92754557/137793386-a6dc49da-7674-4478-a63f-2ffb66a8aea7.JPG)

**Comment by RinatG** [comment]
Эти данные отсутствуют. Когда они появятся в открытых источниках, например, vikings.help, тогда будут добавлены и в калькулятор. К сожалению, Plarium не предоставляет эти справочные данные для сторонних разработчиков подобных инструментов.
