### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by stillfreeua** [RinatG/vikplan.com#22]
привет!
спасибо за труд и помощь игрокам викингов!
нашел ошибку - поправьте пожалуйста (дворец на 37 уровне 0 пропущен в колонке времени стройки)
![image](https://user-images.githubusercontent.com/94202139/141540978-0ec4248c-12a0-4f7e-826b-d9be3aaf6bc1.png)

**Comment by RinatG** [comment]
исправлена ошибка во времени строительства здания Дворец 37ур.
